namespace OGT
{
    using System.Collections.Generic;
    using System.Text;
    using UnityEditor;

    public static class GenerateMenuItems
    {
        public static void Generate()
        {
            var menuItems = GetAllMenuItems();
            var result = new StringBuilder();
            result.AppendLine("// <auto-generated>");
            result.AppendLine("namespace OGT.Generated");
            result.AppendLine("{");
            result.AppendLine("    public static class GeneratedMenuItems");
            result.AppendLine("    {");

            foreach (var menuItem in menuItems)
            {
                if (menuItem != menuItems[0])
                {
                    result.AppendLine();
                }

                // -------------------- Validate Menu Item --------------------
                if (!string.IsNullOrEmpty(menuItem.ValidateBody))
                {
                    result.AppendLine($"        [UnityEditor.MenuItem(\"{menuItem.MenuPath}\", true)]");
                    result.AppendLine($"        public static bool {menuItem.MethodName}Validate()");
                    result.AppendLine(@"        {");

                    foreach (var line in menuItem.ValidateBody.Split('\n'))
                    {
                        result.Append("            ");
                        result.AppendLine(line);
                    }

                    result.AppendLine(@"        }");
                    result.AppendLine();
                }

                // -------------------- Menu Item --------------------
                if (menuItem.Priority == null)
                {
                    result.AppendLine($"        [UnityEditor.MenuItem(\"{menuItem.MenuPath}\")]");
                }
                else
                {
                    result.AppendLine($"        [UnityEditor.MenuItem(\"{menuItem.MenuPath}\", false, {menuItem.Priority.Value})]");
                }

                result.AppendLine($"        public static void {menuItem.MethodName}()");
                result.AppendLine(@"        {");

                foreach (var line in menuItem.MethodBody.Split('\n'))
                {
                    result.Append("            ");
                    result.AppendLine(line);
                }

                result.AppendLine(@"        }");
            }

            result.AppendLine("    }");
            result.AppendLine("}");

            FileUtil.CreateOrUpdateFile(result.ToString(), System.IO.Path.Combine(ProjectSettingsGeneral.Instance.GeneratedOutputDirectory, "Editor", "GeneratedMenuItems.cs"), true);
        }

        private static List<MenuItemData> GetAllMenuItems()
        {
            var results = new List<MenuItemData>();

            // Using reflection to find all methods with the GenerateMenuItemsAttribute
            foreach (var method in TypeCache.GetMethodsWithAttribute<GenerateMenuItemsAttribute>())
            {
                var parameters = method.GetParameters();

                if (method.IsStatic && parameters.Length == 1 && parameters[0].ParameterType == typeof(List<MenuItemData>))
                {
                    method.Invoke(null, new object[] { results });
                }
                else
                {
                    OGTLogger.OGTEditor.LogError($"Method {method.DeclaringType.FullName}.{method.Name} has the GenerateMenuItemsAttribute but does not have the correct signature. It must be static and accept a single parameter of type List<MenuItemData>.");
                }
            }
                                    
            return results;
        }
    }
}
